"use client";

import jsPDF from "jspdf";

export type LetterData = {
  employeeName: string;
  arabicName?: string;
  employeeNumber: string;
  jobTitle?: string;
  department?: string;
  nationality?: string;
  startDate?: string;
  basicSalary?: number;
  housingAllowance?: number;
  transportAllowance?: number;
  otherAllowance?: number;
  companyName?: string;
  issueDate?: string;
  // ── Branding (per-tenant) ──
  logoDataUrl?: string;     // base64 data URL of the logo
  primaryColor?: string;    // hex e.g. "#0284C7"
  commercialReg?: string;
  taxNumber?: string;
  companyAddress?: string;
  companyPhone?: string;
  companyEmail?: string;
};

/** يحوّل hex إلى [r,g,b] عشان jsPDF */
function hexToRgb(hex: string | undefined, fallback: [number, number, number] = [2, 132, 199]): [number, number, number] {
  if (!hex) return fallback;
  const m = hex.match(/^#?([0-9a-fA-F]{6})$/);
  if (!m) return fallback;
  const n = parseInt(m[1], 16);
  return [(n >> 16) & 0xff, (n >> 8) & 0xff, n & 0xff];
}

function totalSalary(d: LetterData) {
  return (d.basicSalary ?? 0) + (d.housingAllowance ?? 0) + (d.transportAllowance ?? 0) + (d.otherAllowance ?? 0);
}

function fmt(n: number) {
  return n.toLocaleString("ar-SA", { minimumFractionDigits: 2 });
}

function base(doc: jsPDF, company: string, title: string, issueDate: string, opts?: { logoDataUrl?: string; primaryColor?: string }) {
  const [r, g, b] = hexToRgb(opts?.primaryColor);
  doc.setFont("helvetica");

  // Header bar — لون البراند
  doc.setFillColor(r, g, b);
  doc.rect(0, 0, 210, 28, "F");

  // Logo (يسار) — لو موجود
  if (opts?.logoDataUrl) {
    try {
      // PNG / JPEG only — SVG غير مدعوم في jsPDF بدون lib إضافية
      const fmt = opts.logoDataUrl.startsWith("data:image/png") ? "PNG"
                : opts.logoDataUrl.startsWith("data:image/jpeg") ? "JPEG"
                : opts.logoDataUrl.startsWith("data:image/jpg")  ? "JPEG"
                : null;
      if (fmt) doc.addImage(opts.logoDataUrl, fmt, 8, 4, 20, 20);
    } catch { /* skip logo on error */ }
  }

  // اسم الشركة في الـ header
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text(company, 105, 14, { align: "center" });
  doc.setFontSize(9);
  doc.text("HR Management System", 105, 22, { align: "center" });

  // Title
  doc.setTextColor(r, g, b);
  doc.setFontSize(15);
  doc.text(title, 105, 44, { align: "center" });
  doc.setDrawColor(r, g, b);
  doc.setLineWidth(0.5);
  doc.line(20, 47, 190, 47);

  // Issue date (right side)
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(9);
  doc.text(`Date: ${issueDate}`, 190, 36, { align: "right" });

  return 58;
}

function row(doc: jsPDF, label: string, value: string, y: number) {
  doc.setTextColor(71, 85, 105);
  doc.setFontSize(10);
  doc.text(`${label}:`, 190, y, { align: "right" });
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text(value, 130, y, { align: "right" });
  return y + 9;
}

function footer(doc: jsPDF, opts?: { commercialReg?: string; taxNumber?: string; address?: string; phone?: string; email?: string }) {
  const pageH = doc.internal.pageSize.height;
  doc.setFillColor(248, 250, 252);
  doc.rect(0, pageH - 22, 210, 22, "F");
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);

  // سطر بيانات الشركة (لو موجودة)
  const lines: string[] = [];
  if (opts?.commercialReg) lines.push(`CR: ${opts.commercialReg}`);
  if (opts?.taxNumber)     lines.push(`VAT: ${opts.taxNumber}`);
  if (opts?.phone)         lines.push(`Tel: ${opts.phone}`);
  if (opts?.email)         lines.push(opts.email);
  if (lines.length) {
    doc.text(lines.join("  •  "), 105, pageH - 14, { align: "center" });
  }
  if (opts?.address) {
    doc.text(opts.address, 105, pageH - 8, { align: "center", maxWidth: 180 });
  } else {
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by MawaridX HR System", 105, pageH - 8, { align: "center" });
  }
}

/** خطاب تعريف بالراتب */
export function generateSalaryCertificate(data: LetterData) {
  const doc = new jsPDF();
  const company = data.companyName ?? "HR Company";
  const issueDate = data.issueDate ?? new Date().toLocaleDateString("en-SA");
  let y = base(doc, company, "Salary Certificate — شهادة راتب", issueDate, { logoDataUrl: data.logoDataUrl, primaryColor: data.primaryColor });

  doc.setTextColor(30, 64, 175);
  doc.setFontSize(10);
  doc.text("To Whom It May Concern,", 20, y);
  y += 10;

  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  const intro = `This is to certify that the below-named employee is currently employed at ${company}.`;
  doc.text(intro, 20, y, { maxWidth: 170 });
  y += 16;

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(18, y - 4, 174, 90, 3, 3, "F");
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.roundedRect(18, y - 4, 174, 90, 3, 3, "S");

  y = row(doc, "Employee Name", data.employeeName, y + 6);
  if (data.arabicName) y = row(doc, "Arabic Name", data.arabicName, y);
  y = row(doc, "Employee No.", data.employeeNumber, y);
  if (data.jobTitle) y = row(doc, "Job Title", data.jobTitle, y);
  if (data.department) y = row(doc, "Department", data.department, y);
  if (data.nationality) y = row(doc, "Nationality", data.nationality === "saudi" ? "Saudi" : "Non-Saudi", y);
  if (data.startDate) y = row(doc, "Start Date", new Date(data.startDate).toLocaleDateString("en-SA"), y);
  y += 4;

  doc.setDrawColor(226, 232, 240);
  doc.line(25, y, 185, y);
  y += 8;

  y = row(doc, "Basic Salary", `SAR ${fmt(data.basicSalary ?? 0)}`, y);
  if (data.housingAllowance) y = row(doc, "Housing Allowance", `SAR ${fmt(data.housingAllowance)}`, y);
  if (data.transportAllowance) y = row(doc, "Transport Allowance", `SAR ${fmt(data.transportAllowance)}`, y);
  if (data.otherAllowance) y = row(doc, "Other Allowance", `SAR ${fmt(data.otherAllowance)}`, y);

  doc.setTextColor(2, 132, 199);
  doc.setFontSize(11);
  y += 4;
  y = row(doc, "Total Monthly Salary", `SAR ${fmt(totalSalary(data))}`, y);

  y += 20;
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(9);
  doc.text("Issued upon request for official use only.", 20, y);
  y += 16;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text("Authorized Signature: ___________________", 20, y);
  doc.text("Official Stamp:", 130, y);

  footer(doc, {
    commercialReg: data.commercialReg,
    taxNumber:     data.taxNumber,
    address:       data.companyAddress,
    phone:         data.companyPhone,
    email:         data.companyEmail,
  });
  doc.save(`salary-certificate-${data.employeeNumber}.pdf`);
}

/** خطاب توظيف */
export function generateEmploymentLetter(data: LetterData) {
  const doc = new jsPDF();
  const company = data.companyName ?? "HR Company";
  const issueDate = data.issueDate ?? new Date().toLocaleDateString("en-SA");
  let y = base(doc, company, "Employment Letter — خطاب توظيف", issueDate, { logoDataUrl: data.logoDataUrl, primaryColor: data.primaryColor });

  doc.setTextColor(30, 64, 175);
  doc.setFontSize(10);
  doc.text("To Whom It May Concern,", 20, y);
  y += 12;

  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  const body = `This is to confirm that ${data.employeeName} (Employee No. ${data.employeeNumber}) is employed at ${company} as ${data.jobTitle ?? "an employee"}${data.department ? ` in the ${data.department} department` : ""}${data.startDate ? `, since ${new Date(data.startDate).toLocaleDateString("en-SA")}` : ""}.`;
  doc.text(body, 20, y, { maxWidth: 170 });
  y += 24;

  doc.text("The employee is in good standing with the organization.", 20, y);
  y += 20;

  doc.text("This letter is issued upon request and for official purposes only.", 20, y);
  y += 24;

  doc.setTextColor(15, 23, 42);
  doc.text("Authorized Signature: ___________________", 20, y);
  doc.text("Official Stamp:", 130, y);

  footer(doc, {
    commercialReg: data.commercialReg,
    taxNumber:     data.taxNumber,
    address:       data.companyAddress,
    phone:         data.companyPhone,
    email:         data.companyEmail,
  });
  doc.save(`employment-letter-${data.employeeNumber}.pdf`);
}

/** شهادة خبرة */
export function generateExperienceLetter(data: LetterData & { endDate?: string }) {
  const doc = new jsPDF();
  const company = data.companyName ?? "HR Company";
  const issueDate = data.issueDate ?? new Date().toLocaleDateString("en-SA");
  const end = data.endDate ? new Date(data.endDate).toLocaleDateString("en-SA") : new Date().toLocaleDateString("en-SA");
  let y = base(doc, company, "Experience Letter — شهادة خبرة", issueDate, { logoDataUrl: data.logoDataUrl, primaryColor: data.primaryColor });

  doc.setTextColor(30, 64, 175);
  doc.setFontSize(10);
  doc.text("To Whom It May Concern,", 20, y);
  y += 12;

  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  const start = data.startDate ? new Date(data.startDate).toLocaleDateString("en-SA") : "—";
  const body = `This is to certify that ${data.employeeName} worked at ${company} as ${data.jobTitle ?? "an employee"}${data.department ? ` in the ${data.department} department` : ""}, from ${start} to ${end}.`;
  doc.text(body, 20, y, { maxWidth: 170 });
  y += 24;

  doc.text("During their tenure, the employee demonstrated professionalism and fulfilled their responsibilities.", 20, y, { maxWidth: 170 });
  y += 20;

  doc.text("We wish them all the best in their future endeavors.", 20, y);
  y += 24;

  doc.setTextColor(15, 23, 42);
  doc.text("Authorized Signature: ___________________", 20, y);
  doc.text("Official Stamp:", 130, y);

  footer(doc, {
    commercialReg: data.commercialReg,
    taxNumber:     data.taxNumber,
    address:       data.companyAddress,
    phone:         data.companyPhone,
    email:         data.companyEmail,
  });
  doc.save(`experience-letter-${data.employeeNumber}.pdf`);
}
