"use client";

import jsPDF from "jspdf";

export type LetterData = {
  employeeName: string;
  arabicName?: string;
  employeeNumber: string;
  jobTitle?: string;
  department?: string;
  nationality?: string;
  startDate?: string;
  basicSalary?: number;
  housingAllowance?: number;
  transportAllowance?: number;
  otherAllowance?: number;
  companyName?: string;
  issueDate?: string;
};

function totalSalary(d: LetterData) {
  return (d.basicSalary ?? 0) + (d.housingAllowance ?? 0) + (d.transportAllowance ?? 0) + (d.otherAllowance ?? 0);
}

function fmt(n: number) {
  return n.toLocaleString("ar-SA", { minimumFractionDigits: 2 });
}

function base(doc: jsPDF, company: string, title: string, issueDate: string) {
  doc.setFont("helvetica");
  // Header
  doc.setFillColor(2, 132, 199);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text("MawaridX", 105, 12, { align: "center" });
  doc.setFontSize(10);
  doc.text(company, 105, 20, { align: "center" });

  // Title
  doc.setTextColor(2, 132, 199);
  doc.setFontSize(15);
  doc.text(title, 105, 44, { align: "center" });
  doc.setDrawColor(2, 132, 199);
  doc.setLineWidth(0.5);
  doc.line(20, 47, 190, 47);

  // Issue date (right side)
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(9);
  doc.text(`Date: ${issueDate}`, 190, 36, { align: "right" });

  return 58;
}

function row(doc: jsPDF, label: string, value: string, y: number) {
  doc.setTextColor(71, 85, 105);
  doc.setFontSize(10);
  doc.text(`${label}:`, 190, y, { align: "right" });
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text(value, 130, y, { align: "right" });
  return y + 9;
}

function footer(doc: jsPDF) {
  const pageH = doc.internal.pageSize.height;
  doc.setFillColor(248, 250, 252);
  doc.rect(0, pageH - 20, 210, 20, "F");
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(8);
  doc.text("This letter is generated by MawaridX HR System", 105, pageH - 8, { align: "center" });
}

/** خطاب تعريف بالراتب */
export function generateSalaryCertificate(data: LetterData) {
  const doc = new jsPDF();
  const company = data.companyName ?? "HR Company";
  const issueDate = data.issueDate ?? new Date().toLocaleDateString("en-SA");
  let y = base(doc, company, "Salary Certificate — شهادة راتب", issueDate);

  doc.setTextColor(30, 64, 175);
  doc.setFontSize(10);
  doc.text("To Whom It May Concern,", 20, y);
  y += 10;

  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  const intro = `This is to certify that the below-named employee is currently employed at ${company}.`;
  doc.text(intro, 20, y, { maxWidth: 170 });
  y += 16;

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(18, y - 4, 174, 90, 3, 3, "F");
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.roundedRect(18, y - 4, 174, 90, 3, 3, "S");

  y = row(doc, "Employee Name", data.employeeName, y + 6);
  if (data.arabicName) y = row(doc, "Arabic Name", data.arabicName, y);
  y = row(doc, "Employee No.", data.employeeNumber, y);
  if (data.jobTitle) y = row(doc, "Job Title", data.jobTitle, y);
  if (data.department) y = row(doc, "Department", data.department, y);
  if (data.nationality) y = row(doc, "Nationality", data.nationality === "saudi" ? "Saudi" : "Non-Saudi", y);
  if (data.startDate) y = row(doc, "Start Date", new Date(data.startDate).toLocaleDateString("en-SA"), y);
  y += 4;

  doc.setDrawColor(226, 232, 240);
  doc.line(25, y, 185, y);
  y += 8;

  y = row(doc, "Basic Salary", `SAR ${fmt(data.basicSalary ?? 0)}`, y);
  if (data.housingAllowance) y = row(doc, "Housing Allowance", `SAR ${fmt(data.housingAllowance)}`, y);
  if (data.transportAllowance) y = row(doc, "Transport Allowance", `SAR ${fmt(data.transportAllowance)}`, y);
  if (data.otherAllowance) y = row(doc, "Other Allowance", `SAR ${fmt(data.otherAllowance)}`, y);

  doc.setTextColor(2, 132, 199);
  doc.setFontSize(11);
  y += 4;
  y = row(doc, "Total Monthly Salary", `SAR ${fmt(totalSalary(data))}`, y);

  y += 20;
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(9);
  doc.text("Issued upon request for official use only.", 20, y);
  y += 16;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.text("Authorized Signature: ___________________", 20, y);
  doc.text("Official Stamp:", 130, y);

  footer(doc);
  doc.save(`salary-certificate-${data.employeeNumber}.pdf`);
}

/** خطاب توظيف */
export function generateEmploymentLetter(data: LetterData) {
  const doc = new jsPDF();
  const company = data.companyName ?? "HR Company";
  const issueDate = data.issueDate ?? new Date().toLocaleDateString("en-SA");
  let y = base(doc, company, "Employment Letter — خطاب توظيف", issueDate);

  doc.setTextColor(30, 64, 175);
  doc.setFontSize(10);
  doc.text("To Whom It May Concern,", 20, y);
  y += 12;

  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  const body = `This is to confirm that ${data.employeeName} (Employee No. ${data.employeeNumber}) is employed at ${company} as ${data.jobTitle ?? "an employee"}${data.department ? ` in the ${data.department} department` : ""}${data.startDate ? `, since ${new Date(data.startDate).toLocaleDateString("en-SA")}` : ""}.`;
  doc.text(body, 20, y, { maxWidth: 170 });
  y += 24;

  doc.text("The employee is in good standing with the organization.", 20, y);
  y += 20;

  doc.text("This letter is issued upon request and for official purposes only.", 20, y);
  y += 24;

  doc.setTextColor(15, 23, 42);
  doc.text("Authorized Signature: ___________________", 20, y);
  doc.text("Official Stamp:", 130, y);

  footer(doc);
  doc.save(`employment-letter-${data.employeeNumber}.pdf`);
}

/** شهادة خبرة */
export function generateExperienceLetter(data: LetterData & { endDate?: string }) {
  const doc = new jsPDF();
  const company = data.companyName ?? "HR Company";
  const issueDate = data.issueDate ?? new Date().toLocaleDateString("en-SA");
  const end = data.endDate ? new Date(data.endDate).toLocaleDateString("en-SA") : new Date().toLocaleDateString("en-SA");
  let y = base(doc, company, "Experience Letter — شهادة خبرة", issueDate);

  doc.setTextColor(30, 64, 175);
  doc.setFontSize(10);
  doc.text("To Whom It May Concern,", 20, y);
  y += 12;

  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  const start = data.startDate ? new Date(data.startDate).toLocaleDateString("en-SA") : "—";
  const body = `This is to certify that ${data.employeeName} worked at ${company} as ${data.jobTitle ?? "an employee"}${data.department ? ` in the ${data.department} department` : ""}, from ${start} to ${end}.`;
  doc.text(body, 20, y, { maxWidth: 170 });
  y += 24;

  doc.text("During their tenure, the employee demonstrated professionalism and fulfilled their responsibilities.", 20, y, { maxWidth: 170 });
  y += 20;

  doc.text("We wish them all the best in their future endeavors.", 20, y);
  y += 24;

  doc.setTextColor(15, 23, 42);
  doc.text("Authorized Signature: ___________________", 20, y);
  doc.text("Official Stamp:", 130, y);

  footer(doc);
  doc.save(`experience-letter-${data.employeeNumber}.pdf`);
}
