"use client";

import { createContext, useContext, useEffect, useState } from "react";

type Lang = "ar" | "en";
type LangContextType = { lang: Lang; toggle: () => void; t: (key: string) => string };

const LangContext = createContext<LangContextType>({ lang: "ar", toggle: () => {}, t: (k) => k });

const translations: Record<string, string> = {
  // ─── Sidebar HR ───────────────────────────────────────────────
  "لوحة التحكم": "Dashboard",
  "الموظفون": "Employees",
  "الهيكل التنظيمي": "Org Chart",
  "الأقسام": "Departments",
  "مواقع العمل": "Locations",
  "الحضور والإجازات": "Attendance & Leaves",
  "التقويم": "Calendar",
  "الطلبات": "Requests",
  "الإعلانات": "Announcements",
  "التقارير": "Reports",
  "الرواتب": "Salaries",
  "التوظيف": "Recruitment",
  "تقييم الأداء": "Evaluations",
  "التدريب والتطوير": "Training",
  "سجل التدقيق": "Audit Log",
  "الإعدادات": "Settings",
  "تسجيل الخروج": "Logout",
  "نظام الموارد البشرية": "HR System",
  // ─── Portal sidebar ───────────────────────────────────────────
  "بوابة الموظف": "Employee Portal",
  "الرئيسية": "Home",
  "البصمة الجغرافية": "Geo Check-in",
  "الحضور والانصراف": "Attendance",
  "طلبات الإجازة": "Leave Requests",
  "طلباتي": "My Requests",
  "كشف الراتب": "Salary Slip",
  "ملفي الشخصي": "My Profile",
  "طلبات الفريق": "Team Requests",
  "لوحة الفريق": "Team Dashboard",
  "عهدتي": "My Custodies",
  // ─── Common actions ───────────────────────────────────────────
  "مرحباً": "Welcome",
  "حفظ": "Save",
  "إلغاء": "Cancel",
  "تعديل": "Edit",
  "حذف": "Delete",
  "إضافة": "Add",
  "بحث": "Search",
  "تصدير": "Export",
  "طباعة": "Print",
  "تحديث": "Refresh",
  "عرض الكل": "View All",
  "التفاصيل": "Details",
  "إغلاق": "Close",
  "تأكيد": "Confirm",
  "رفض": "Reject",
  "موافقة": "Approve",
  "موافقة نهائية": "Final Approval",
  "موافقة المدير": "Manager Approval",
  "إرسال": "Send",
  "حفظ التغييرات": "Save Changes",
  "جارٍ الحفظ...": "Saving...",
  "جارٍ الإرسال...": "Sending...",
  "جارٍ التحميل...": "Loading...",
  "تم الحفظ!": "Saved!",
  "تم بنجاح": "Done successfully",
  // ─── Status labels ────────────────────────────────────────────
  "حاضر": "Present",
  "غائب": "Absent",
  "متأخر": "Late",
  "نصف دوام": "Half Day",
  "إجازة": "On Leave",
  "موافق": "Approved",
  "موافق عليها": "Approved",
  "مرفوض": "Rejected",
  "مرفوضة": "Rejected",
  "معلق": "Pending",
  "معلقة": "Pending",
  "معتمدة": "Approved",
  "مؤكدة": "Confirmed",
  "مصروف": "Paid",
  "تم الصرف": "Paid",
  "لم يُسجَّل": "Not recorded",
  "لم تُولَّد بعد": "Not generated",
  "نشط": "Active",
  "غير نشط": "Inactive",
  "منتهي": "Terminated",
  "منتهية": "Expired",
  "مفعّل": "Enabled",
  "معطل": "Disabled",
  "بانتظار المدير": "Awaiting Manager",
  "بانتظار الإدارة": "Awaiting HR",
  "بانتظارك": "Awaiting You",
  "قيد المراجعة": "Under Review",
  "مكتمل": "Completed",
  "مُرحَّل": "Carried Over",
  "تم الترحيل": "Carried Over",
  "تم تخطيه": "Skipped",
  // ─── Dashboard ───────────────────────────────────────────────
  "مرحباً بك في نظام الموارد البشرية": "Welcome to the HR System",
  "إجمالي الموظفين": "Total Employees",
  "حضور اليوم": "Today's Attendance",
  "طلبات معلقة": "Pending Requests",
  "تنتظر إجراءك": "Awaiting your action",
  "رواتب الشهر": "Monthly Salaries",
  "حضور آخر 7 أيام": "Last 7 Days Attendance",
  "آخر الإعلانات": "Latest Announcements",
  "تجديد الإقامات": "Iqama Renewals",
  "الموظفون غير السعوديين الذين تنتهي إقامتهم خلال شهرين": "Non-Saudi employees with iqama expiring within 2 months",
  "يوم": "day",
  "أيام": "days",
  "تجديد": "Renew",
  "تاريخ الانتهاء الجديد": "New Expiry Date",
  "حفظ التجديد": "Save Renewal",
  "جارٍ الحفظ": "Saving",
  "المتأخرون اليوم": "Late Today",
  "لا يوجد متأخرون اليوم": "No late employees today",
  "طلبات تنتظر إجراءك": "Requests Awaiting Your Action",
  "لا توجد طلبات معلقة": "No pending requests",
  "إجمالي الصافي": "Total Net",
  "ر.س": "SAR",
  "عام": "General",
  "من": "From",
  "إلى": "To",
  // ─── Employees ────────────────────────────────────────────────
  "إضافة موظف": "Add Employee",
  "إضافة موظف جديد": "Add New Employee",
  "تعديل بيانات الموظف": "Edit Employee",
  "بحث بالاسم أو البريد أو الرقم...": "Search by name, email or number...",
  "لا توجد نتائج للبحث": "No search results",
  "لا يوجد موظفون — ابدأ بإضافة موظف جديد": "No employees — start by adding a new employee",
  "الرقم": "No.",
  "الاسم": "Name",
  "المسمى الوظيفي": "Job Title",
  "القسم": "Department",
  "الراتب": "Salary",
  "الحالة": "Status",
  "إجراءات": "Actions",
  "عرض الملف": "View Profile",
  "هل أنت متأكد من حذف هذا الموظف؟": "Are you sure you want to delete this employee?",
  "إضافة الموظف": "Add Employee",
  // Employee form sections
  "البيانات الشخصية": "Personal Info",
  "البيانات الوظيفية": "Job Info",
  "البيانات المالية": "Financial Info",
  "العنوان": "Address",
  "الاسم الأول": "First Name",
  "اسم العائلة": "Last Name",
  "الاسم بالعربي": "Arabic Name",
  "البريد الإلكتروني": "Email",
  "رقم الهاتف": "Phone",
  "رقم الهوية": "ID Number",
  "تاريخ الميلاد": "Date of Birth",
  "الجنس": "Gender",
  "ذكر": "Male",
  "أنثى": "Female",
  "الحالة الاجتماعية": "Marital Status",
  "أعزب": "Single",
  "متزوج": "Married",
  "مطلق": "Divorced",
  "أرمل": "Widowed",
  "الجنسية": "Nationality",
  "سعودي": "Saudi",
  "غير سعودي": "Non-Saudi",
  "تاريخ انتهاء الإقامة": "Iqama Expiry",
  "المنصب": "Position",
  "اختر المنصب": "Select position",
  "مدير": "Manager",
  "مشرف": "Supervisor",
  "موظف": "Employee",
  "اختر القسم": "Select department",
  "بدون قسم": "No department",
  "المدير المباشر": "Direct Manager",
  "بدون مدير": "No manager",
  "نوع التوظيف": "Employment Type",
  "دوام كامل": "Full Time",
  "دوام جزئي": "Part Time",
  "عقد": "Contract",
  "تاريخ المباشرة": "Start Date",
  "موقع العمل / الفرع": "Work Location / Branch",
  "اختر (اختياري)": "Select (optional)",
  "بدون موقع محدد": "No location",
  "الراتب الأساسي (ر.س)": "Basic Salary (SAR)",
  "اسم البنك": "Bank Name",
  "مثال: بنك الراجحي": "e.g. Al Rajhi Bank",
  "رقم الآيبان (IBAN)": "IBAN Number",
  "المدينة": "City",
  "الاسم الأول واسم العائلة والبريد الإلكتروني مطلوبة": "First name, last name and email are required",
  "يرجى تحديد منصب الموظف": "Please select employee position",
  "حدث خطأ أثناء الحفظ، حاول مجدداً": "An error occurred while saving, please try again",
  // ─── Attendance ───────────────────────────────────────────────
  "الحضور": "Attendance",
  "تأخير": "Late",
  "غياب": "Absence",
  "سجلات": "Records",
  "سجل الحضور": "Attendance Log",
  "ملخص الموظفين": "Employee Summary",
  "الإجازات": "Leaves",
  "كل الموظفين": "All Employees",
  "تسجيل": "Register",
  "طلب إجازة": "Request Leave",
  "بحث بالاسم أو الرقم الوظيفي...": "Search by name or employee number...",
  "الموظف": "Employee",
  "التاريخ": "Date",
  "تسجيل الحضور": "Check In",
  "تسجيل الانصراف": "Check Out",
  "عدد ساعات العمل": "Work Hours",
  "لا توجد سجلات لهذا الشهر": "No records for this month",
  "صباحاً": "AM",
  "مساءً": "PM",
  "دقيقة": "min",
  "ساعات": "hours",
  "إجمالي دقائق التأخير": "Total Late Minutes",
  "إجمالي عدد ساعات العمل": "Total Work Hours",
  "الإجمالي": "Total",
  "النوع": "Type",
  "الأيام": "Days",
  "اختر موظف": "Select employee",
  "وقت الدخول": "Check-in Time",
  "وقت الخروج": "Check-out Time",
  "ملاحظات": "Notes",
  "نوع الإجازة": "Leave Type",
  "سنوية": "Annual",
  "مرضية": "Sick",
  "طارئة": "Emergency",
  "بدون راتب": "Unpaid",
  "أمومة": "Maternity",
  "أبوة": "Paternity",
  "السبب": "Reason",
  "عذر طبي": "Medical excuse",
  // ─── Requests ─────────────────────────────────────────────────
  "جميع طلبات الموظفين": "All Employee Requests",
  "الكل": "All",
  "لا توجد طلبات": "No requests",
  "نوع الطلب": "Request Type",
  "تصحيح بصمة": "Attendance Fix",
  "طلب سلفة": "Loan Request",
  "طلب عهدة": "Custody Request",
  "طلب خروج وعودة": "Exit & Return",
  "طلب استقالة": "Resignation",
  "طلب خطاب": "Letter Request",
  "تفاصيل الطلب": "Request Details",
  "المبلغ": "Amount",
  "ملاحظة المدير المباشر": "Manager Note",
  "وافق المدير المباشر — بانتظار موافقتك النهائية": "Manager approved — awaiting your final approval",
  "الموظف ليس لديه مدير مباشر — الطلب يحتاج موافقتك مباشرة": "Employee has no direct manager — request needs your direct approval",
  "الطلب بانتظار موافقة المدير المباشر أولاً": "Request is awaiting manager approval first",
  "ملاحظة الإدارة (اختياري)": "HR Note (optional)",
  "ملاحظة للموظف...": "Note to employee...",
  // ─── Salaries ─────────────────────────────────────────────────
  "توليد الرواتب": "Generate Salaries",
  "إعادة حساب GOSI": "Recalculate GOSI",
  "صرف الجميع": "Pay All",
  "إضافة راتب": "Add Salary",
  "إجمالي الأساسي": "Total Basic",
  "GOSI (موظف + صاحب عمل)": "GOSI (Employee + Employer)",
  "تم الصرف / معلق": "Paid / Pending",
  "الخصومات الثابتة الشهرية": "Monthly Fixed Deductions",
  "خصم": "Deduction",
  "تُطبَّق تلقائياً عند توليد الرواتب": "Applied automatically when generating salaries",
  "إضافة خصم": "Add Deduction",
  "لا توجد خصومات ثابتة مضافة": "No fixed deductions added",
  "جميع الموظفين": "All Employees",
  "شهر": "Month",
  "مُسجَّل من أصل": "Registered of",
  "الأساسي": "Basic",
  "البدلات": "Allowances",
  "الخصومات": "Deductions",
  "المكافآت": "Bonuses",
  "GOSI (موظف)": "GOSI (Employee)",
  "الصافي": "Net",
  "صرف": "Pay",
  "تعديل الراتب": "Edit Salary",
  "الراتب الأساسي": "Basic Salary",
  "أجر إضافي": "Overtime Pay",
  "التأمينات الاجتماعية (GOSI)": "Social Insurance (GOSI)",
  "سعودي (9% + 9%)": "Saudi (9% + 9%)",
  "غير سعودي (2% صاحب عمل)": "Non-Saudi (2% employer)",
  "نصيب الموظف (خصم)": "Employee Share (deduction)",
  "نصيب صاحب العمل": "Employer Share",
  "شامل خصم GOSI": "Including GOSI deduction",
  "تعديل الخصم": "Edit Deduction",
  "إضافة خصم ثابت": "Add Fixed Deduction",
  "اسم الخصم": "Deduction Name",
  "مثال: قرض، غرامة، استقطاع...": "e.g. Loan, Fine, Withholding...",
  "نوع الخصم": "Deduction Type",
  "مبلغ ثابت (ر.س)": "Fixed Amount (SAR)",
  "نسبة مئوية (%)": "Percentage (%)",
  "النسبة (%)": "Percentage (%)",
  "المبلغ (ر.س)": "Amount (SAR)",
  "تطبيق على": "Apply to",
  "عدد أشهر الخصم": "Deduction Months",
  "0 = دائم": "0 = permanent",
  "اتركه 0 للخصم الدائم، أو حدد عدد الأشهر (مثال: 3 = قسط لـ 3 أشهر ويتوقف تلقائياً)": "Leave 0 for permanent, or set months (e.g. 3 = installment for 3 months)",
  "هل تريد حذف هذا الخصم؟": "Are you sure you want to delete this deduction?",
  // ─── Settings ─────────────────────────────────────────────────
  "إعدادات النظام": "System Settings",
  "إعدادات الموقع والدوام": "Location & Schedule Settings",
  "إعدادات الدوام": "Work Schedule",
  "دوام ثابت": "Fixed Schedule",
  "وقت دخول وخروج محدد": "Fixed check-in/out times",
  "دوام مرن": "Flexible Schedule",
  "عدد ساعات يومية فقط": "Daily hours only",
  "وقت الحضور": "Check-in Time",
  "وقت الانصراف": "Check-out Time",
  "مهلة التأخير (دقيقة)": "Late Tolerance (minutes)",
  "يُحسب متأخراً بعد هذه الدقائق": "Counted as late after these minutes",
  "عدد ساعات العمل اليومية المطلوبة": "Required Daily Work Hours",
  "الموظف يجب أن يكمل هذا العدد من الساعات يومياً": "Employee must complete this many hours daily",
  "حفظ إعدادات الدوام": "Save Schedule Settings",
  "تم حفظ إعدادات الدوام بنجاح": "Schedule settings saved successfully",
  "إعدادات البريد الإلكتروني (SMTP)": "Email Settings (SMTP)",
  "تفعيل إرسال البريد:": "Enable email sending:",
  "مفعل": "Enabled",
  "خادم SMTP": "SMTP Server",
  "المنفذ (Port)": "Port",
  "تشفير SSL": "SSL Encryption",
  "البريد / اسم المستخدم": "Email / Username",
  "كلمة المرور / App Password": "Password / App Password",
  "عنوان المرسل": "Sender Address",
  "اختياري — إذا مختلف عن اسم المستخدم": "Optional — if different from username",
  "حفظ إعدادات البريد": "Save Email Settings",
  "إرسال رسالة تجريبية": "Send Test Email",
  "تم حفظ الإعدادات بنجاح": "Settings saved successfully",
  "ترحيل رصيد الإجازات": "Leave Balance Carryover",
  "نقل الرصيد المتبقي من السنة السابقة إلى السنة الجديدة لجميع الموظفين النشطين": "Transfer remaining balance from previous year to new year for all active employees",
  "من سنة": "From Year",
  "إلى سنة": "To Year",
  "أقصى ترحيل سنوي": "Max Annual Carryover",
  "أقصى ترحيل مرضي": "Max Sick Carryover",
  "أقصى ترحيل طارئ": "Max Emergency Carryover",
  "معاينة الأرصدة": "Preview Balances",
  "تنفيذ الترحيل": "Execute Carryover",
  "معاينة أرصدة": "Preview Balances",
  "متبقي سنوي": "Remaining Annual",
  "متبقي مرضي": "Remaining Sick",
  "متبقي طارئ": "Remaining Emergency",
  "مُرحّل سنوي": "Annual Carried",
  "الرصيد الجديد": "New Balance",
  "عرض التفاصيل": "Show Details",
  "إخفاء التفاصيل": "Hide Details",
  "مواقع العمل والبصمة الجغرافية": "Work Locations & Geo-attendance",
  "إضافة الفروع وتحديد مواقعها على الخريطة ونطاق البصمة": "Add branches and set map location and attendance radius",
  "إدارة المواقع": "Manage Locations",
  // ─── Portal Home ─────────────────────────────────────────────
  "صباح الخير": "Good Morning",
  "مساء الخير": "Good Afternoon",
  "مساء النور": "Good Evening",
  "الدوام مكتمل": "Shift Complete",
  "تسجيل الحضور / تسجيل الانصراف": "Check In / Check Out",
  "دخول": "Check In",
  "تصحيح البصمة": "Fix Attendance",
  "طلب عمل": "Work Request",
  "طلباتك": "Your Requests",
  "تم مراجعة جميع الطلبات": "All requests reviewed",
  "لا يوجد جديد اليوم": "Nothing new today",
  "الرصيد المتبقي": "Remaining Balance",
  "الرصيد المستحق": "Entitled Balance",
  "سجلات غير مكتملة": "Incomplete Records",
  // ─── Portal Attendance ───────────────────────────────────────
  "تسجيل الحضور والانصراف": "Check In & Out",
  "جارٍ تحديد موقعك...": "Locating you...",
  "أنت داخل نطاق": "You are within range",
  "أنت خارج النطاق —": "You are out of range —",
  "المسموح": "allowed",
  "تعذّر تحديد الموقع — تأكد من تفعيل GPS": "Could not determine location — enable GPS",
  "لم يُحدَّد موقع المكتب بعد — تواصل مع الإدارة": "Office location not set — contact HR",
  "لم تُسجّل حضورك بعد": "You haven't checked in yet",
  "سيُطلب منك السماح بالموقع عند الضغط": "Location permission will be requested on click",
  "سجل الشهر": "Monthly Record",
  "لا توجد سجلات هذا الشهر": "No records this month",
  "أيام حضور هذا الشهر": "Attendance Days This Month",
  "أيام غياب هذا الشهر": "Absence Days This Month",
  "أيام تأخر هذا الشهر": "Late Days This Month",
  // ─── Portal Requests ─────────────────────────────────────────
  "تقديم ومتابعة طلباتك": "Submit and track your requests",
  "طلب جديد": "New Request",
  "لا توجد طلبات — اضغط \"طلب جديد\" للبدء": "No requests — click \"New Request\" to start",
  "اختر نوع الطلب": "Select request type",
  "عنوان مختصر للطلب": "Short request title",
  "من تاريخ": "From date",
  "إلى تاريخ": "To date",
  "تاريخ السداد": "Repayment Date",
  "وقت العودة": "Return Time",
  "تاريخ البصمة المراد تصحيحها": "Date to fix",
  "نوع البصمة": "Attendance Type",
  "اختر نوع البصمة": "Select type",
  "بصمة دخول": "Check-in",
  "بصمة خروج": "Check-out",
  "الوقت الصحيح": "Correct Time",
  "التفاصيل والملاحظات": "Details & Notes",
  "اكتب تفاصيل إضافية...": "Write additional details...",
  "سيتم إرسال الطلب مباشرة إلى الإدارة": "Request will be sent directly to HR",
  "يرجى اختيار نوع الطلب": "Please select request type",
  "يرجى كتابة عنوان الطلب": "Please write request title",
  "يرجى تحديد تاريخ البصمة": "Please set attendance date",
  "يرجى اختيار نوع البصمة": "Please select attendance type",
  "يرجى إدخال الوقت الصحيح": "Please enter correct time",
  "إرسال الطلب": "Submit Request",
  // ─── Custodies ───────────────────────────────────────────────
  "إجمالي العهد": "Total Custodies",
  "مستلمة": "Received",
  "متابعة حالة العهد المُسلَّمة لك": "Track your assigned custodies",
  "لا توجد عهد مسجلة لك": "No custodies registered for you",
  // ─── Leave balance ───────────────────────────────────────────
  "متبقي": "Remaining",
  "مُستخدم": "Used",
  "مستحق": "Entitled",
  // ─── Profile ─────────────────────────────────────────────────
  "المعلومات الشخصية": "Personal Information",
  "معلومات الوظيفة": "Job Information",
  "معلومات مالية": "Financial Information",
  "رقم الموظف": "Employee Number",
  "الإدارة": "Department",
  "تاريخ الانضمام": "Join Date",
  "نوع العقد": "Contract Type",
  "الحساب البنكي": "Bank Account",
  "الآيبان": "IBAN",
  // ─── Recruitment ─────────────────────────────────────────────
  "الوظائف المفتوحة": "Open Positions",
  "إضافة وظيفة": "Add Job",
  "المتقدمون": "Applicants",
  "المقابلات": "Interviews",
  "مغلقة": "Closed",
  "مفتوحة": "Open",
  "تاريخ الإغلاق": "Close Date",
  "اسم المتقدم": "Applicant Name",
  "موعد المقابلة": "Interview Date",
  "جديد": "New",
  "مقبول": "Accepted",
  // ─── Evaluations ─────────────────────────────────────────────
  "تقييمات الأداء": "Performance Evaluations",
  "إضافة تقييم": "Add Evaluation",
  "الفترة": "Period",
  "الدرجة": "Score",
  "التقدير": "Grade",
  "نقاط القوة": "Strengths",
  "مجالات التحسين": "Improvements",
  "الأهداف": "Goals",
  "مسودة": "Draft",
  "نهائي": "Final",
  // ─── Training ────────────────────────────────────────────────
  "برامج التدريب": "Training Programs",
  "إضافة برنامج": "Add Program",
  "المدرب": "Instructor",
  "المدة": "Duration",
  "الموقع": "Location",
  "داخلي": "Internal",
  "خارجي": "External",
  "مخطط": "Planned",
  "جارٍ": "In Progress",
  "الشهادة": "Certificate",
  "مسجل": "Enrolled",
  // ─── Audit Log ────────────────────────────────────────────────
  "سجل المراجعة": "Audit Log",
  "المستخدم": "User",
  "الإجراء": "Action",
  "الجهة": "Entity",
  "الوقت": "Time",
  "إنشاء": "Create",
  // ─── Reports ─────────────────────────────────────────────────
  "التقارير والإحصاءات": "Reports & Statistics",
  "تقرير الحضور": "Attendance Report",
  "تقرير الرواتب": "Salary Report",
  "تقرير الإجازات": "Leave Report",
  "تحميل PDF": "Download PDF",
  "تحميل Excel": "Download Excel",
  // ─── Misc ────────────────────────────────────────────────────
  "لا توجد بيانات": "No data",
  "إجمالي": "Total",
  "الشهر": "Month",
  "السنة": "Year",
  "الصفحة": "Page",
  "السابق": "Previous",
  "التالي": "Next",
  "عرض": "Show",
  "صف": "rows",
  "تسجيل الدخول": "Login",
  "كلمة المرور": "Password",
  "نسيت كلمة المرور؟": "Forgot password?",
  "موظف جديد؟ سجّل حسابك": "New employee? Register",
  "متابعة أداء وحضور فريق العمل": "Monitor team performance and attendance",
  "أعضاء الفريق": "Team Members",
  // ─── Allowances ──────────────────────────────────────────────
  "بدل السكن": "Housing Allowance",
  "بدل المواصلات": "Transport Allowance",
  "بدل أخرى": "Other Allowance",
  "إجمالي الراتب": "Total Salary",
  // ─── Calendar ────────────────────────────────────────────────
  "عرض الحضور والإجازات على شكل تقويم شهري": "View attendance and leaves as a monthly calendar",
  "حضور": "Present",
  "إجازات موافق عليها": "Approved Leaves",
  "تفاصيل يوم": "Day Details",
  "لا توجد سجلات لهذا اليوم": "No records for this day",
  "سجلات الحضور": "Attendance Records",
  "إجازات": "Leaves",
  "تقويم الحضور": "Attendance Calendar",
  "عرض حضورك وإجازاتك على التقويم": "View your attendance and leaves on the calendar",
  "تقويمي": "My Calendar",
};

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("ar");

  useEffect(() => {
    const saved = localStorage.getItem("hr_lang") as Lang | null;
    if (saved) {
      setLang(saved);
      document.documentElement.lang = saved;
      document.documentElement.dir = saved === "ar" ? "rtl" : "ltr";
    }
  }, []);

  const toggle = () => {
    const next = lang === "ar" ? "en" : "ar";
    setLang(next);
    localStorage.setItem("hr_lang", next);
    document.documentElement.lang = next;
    document.documentElement.dir = next === "ar" ? "rtl" : "ltr";
  };

  const t = (key: string) => {
    if (lang === "ar") return key;
    return translations[key] ?? key;
  };

  return <LangContext.Provider value={{ lang, toggle, t }}>{children}</LangContext.Provider>;
}

export const useLang = () => useContext(LangContext);
